pms/parking_premises/urls.py
from django.urls import path
from . import views

app_name = "parking_premises"

urlpatterns = [
    path("premises-list", views.PremiseListView.as_view(), name="premises_list"),
    path("premises-create", views.PremiseCreateView.as_view(), name="premises_create"),
    path(
        "premises-delete/<int:pk>/",
        views.PremiseDeleteView.as_view(),
        name="premises_delete",
    ),
    path("slot-list", views.SlotListView.as_view(), name="slot_list"),
    path("slot-create", views.SlotCreateView.as_view(), name="slot_create"),
    path("slot-delete/<int:pk>/", views.SlotDeleteView.as_view(), name="slot_delete"),
    path("all_slots", views.AllSlotView.as_view(), name="all_slots"),
    path(
        "book_parking_slot/",
        views.BookParkingSlotView.as_view(),
        name="book_parking_slot",
    ),
]

pms/pms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('parking/', include('parking_premises.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pms/users/urls.py
from django.urls import path
from . import views

# Create your urls here.

app_name = "users"

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("register", views.UserCreateView.as_view(), name="register"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("user-dashboard", views.UserDashboard.as_view(), name="user_dashboard"),
    path("admin-dashboard", views.AdminDashboard.as_view(), name="admin_dashboard"),
]

pms/templates/common/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Parking Managment</title>
    {% include "common/header.html" %}
    {% block extra_css %} {# Override this in templates to add extra CSS #} {% endblock extra_css %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'common/sidebar.html' %}


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#"></a></li>
<!--              <li class="breadcrumb-item active">Dashboard v1</li>-->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        {% block content %}

        {% endblock content %}

      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2023 <a href="#">Parking Managemet</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b></b>
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
{% include 'common/footer.html' %}
{% block extra_js %}
{% endblock %}
</body>
</html>

pms/templates/common/footer.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>

<script>
setTimeout(function(){
  if ($('#msg').length > 0) {
    $('#msg').remove();
  }
}, 2000)
</script>

pms/templates/common/header.html
{% load static %}
<!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">

pms/templates/common/messaging.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

pms/templates/common/pegination.html
<ul class="pagination pagination-sm m-0 float-right">
    {% if page_obj.has_previous %}
         <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">« Previous</a></li>
        {% if page_obj.number > 3 %}
             <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            {% if page_obj.number > 4 %}
                <span>...</span>
            {% endif %}
        {% endif %}
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
             <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
             <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
            <span>...</span>
             <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
        {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
             <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
        {% endif %}
         <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next »</a></li>
    {% endif %}
</ul>

pms/templates/common/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">PMS</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                {% if request.user.user_type == "admin" %}
                    <li class="nav-item">
                        <a href="{% url 'parking_premises:premises_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Manage Premises
                                <!--                <span class="right badge badge-danger">New</span>-->
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'parking_premises:slot_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Manage Slots
                                <!--                <span class="right badge badge-danger">New</span>-->
                            </p>
                        </a>
                    </li>
                {% else %}
                     <li class="nav-item">
                        <a href="{% url 'parking_premises:all_slots' %}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Parking Slots
                                <!--                <span class="right badge badge-danger">New</span>-->
                            </p>
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'users:logout' %}" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Logout
                            <!--                <span class="right badge badge-danger">New</span>-->
                        </p>
                    </a>
                </li>


            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>