pms/parking_premises/urls.py
from django.urls import path
from . import views

app_name = "parking_premises"

urlpatterns = [
    path("premises-list", views.PremiseListView.as_view(), name="premises_list"),
    path("premises-create", views.PremiseCreateView.as_view(), name="premises_create"),
    path(
        "premises-delete/<int:pk>/",
        views.PremiseDeleteView.as_view(),
        name="premises_delete",
    ),
    path("slot-list", views.SlotListView.as_view(), name="slot_list"),
    path("slot-create", views.SlotCreateView.as_view(), name="slot_create"),
    path("slot-delete/<int:pk>/", views.SlotDeleteView.as_view(), name="slot_delete"),
    path("all_slots", views.AllSlotView.as_view(), name="all_slots"),
    path(
        "book_parking_slot/",
        views.BookParkingSlotView.as_view(),
        name="book_parking_slot",
    ),
]

pms/pms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('parking/', include('parking_premises.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pms/parking_premises/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel, ActivatorModel
from users.models import UserMaster

# Create your models here.


class Premises(TimeStampedModel, ActivatorModel):
    premise_user = models.ForeignKey(
        UserMaster, on_delete=models.CASCADE, related_name="premise_users"
    )
    premise_name = models.CharField(max_length=50)
    address = models.TextField()
    authorized_person_name = models.CharField(max_length=25)
    authorized_person_contact = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.premise_name}"


class Slot(TimeStampedModel, ActivatorModel):
    CAR = "car"
    TWO_WHEELER = "two_wheeler"
    THREE_WHEELER = "three_wheeler"

    VEHICLE_TYPE = (
        (CAR, "Car"),
        (TWO_WHEELER, "Two wheeler"),
        (THREE_WHEELER, "Three wheeler"),
    )
    premise_slot = models.ForeignKey(
        Premises, on_delete=models.CASCADE, related_name="premises_slots"
    )
    vehicle_type = models.CharField(max_length=20, choices=VEHICLE_TYPE)
    price = models.IntegerField()

    def __str__(self):
        return f"{self.vehicle_type} - {self.price}"


class BookParking(TimeStampedModel, ActivatorModel):
    slot_book = models.ForeignKey(
        Slot, on_delete=models.CASCADE, related_name="slot_books"
    )
    user = models.ForeignKey(
        UserMaster, on_delete=models.CASCADE, related_name="user_bookings"
    )
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

pms/templates/premises/all_slots.html
{% extends "common/base.html" %}
{% block content %}
{% include 'common/messaging.html' %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">All Slots</h3>

    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <form>
            <div class="row">
                <div class="col-md-3">
                    <label>Vehicle Type:</label>
                    <select class="form-control" name="car_type">
                        <option value="car">Car</option>
                        <option value="two_wheeler">Two Wheeler</option>
                        <option value="three_wheeler">Three Wheeler</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label>Start Date and time:</label>
                     <div class="input-group date" id="reservationdatetime" data-target-input="nearest">
                        <input type="text" required  name="start_date" class="form-control datetimepicker-input" data-target="#reservationdatetime"/>
                        <div class="input-group-append" data-target="#reservationdatetime" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <label>End Date and time:</label>
                     <div class="input-group date" id="reservationdatetime_end" data-target-input="nearest">
                        <input type="text" required name="end_date" class="form-control datetimepicker-input" data-target="#reservationdatetime_end"/>
                        <div class="input-group-append" data-target="#reservationdatetime_end" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                 <div class="col-md-3">
                     <label></label>
                     <button type="submit" class="btn btn-primary">Search</button>
                 </div>
            </div>

        </form>
        {% if all_slots%}
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Premises Name</th>
                <th>Vehicle Type</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>

                {% for slot_obj in all_slots %}
                <tr>
                    <td>{{ slot_obj.premise_slot.premise_name }}</td>
                    <td>{{ slot_obj.get_vehicle_type_display }}</td>
                    <td>{{ slot_obj.price }}</td>
                    <td>
                        <form action="{% url 'parking_premises:book_parking_slot' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="book_start_date" value="{{ start_date }}">
                            <input type="hidden" name="book_end_date" value="{{ end_date }}">
                            <input type="hidden" name="slot_id" value="{{ slot_obj.id }}">
                             <button type="submit" class="btn btn-danger">Book</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
         {% else %}
<!--           Please fill the search data.-->
          {% endif %}
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        {% include "common/pegination.html" %}
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {
        var word = document.getElementById("reservationdatetime").value;
        console.log(word);
        console.log("nayan");

    });
console.log("ddd");
    $('#reservationdatetime').datetimepicker({ format: 'DD/MM/YYYY HH:mm', icons: { time: 'far fa-clock' } });
    $('#reservationdatetime_end').datetimepicker({ format: 'DD/MM/YYYY HH:mm', icons: { time: 'far fa-clock' } });

</script>
{% endblock%}

pms/templates/premises/premise_create.html
{% extends "common/base.html" %}
{% block content %}
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Premises Form</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label>Premises Name</label>
                {{ form.premise_name }}
            </div>
             <div class="form-group">
                <label>Address</label>
                {{ form.address }}
            </div>
            <div class="form-group">
                <label>Authorized Person Name</label>
                {{ form.authorized_person_name }}
            </div>
            <div class="form-group">
                <label>Authorized Person Contact</label>
                {{ form.authorized_person_contact }}
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {

    });

</script>
{% endblock%}

pms/templates/premises/premises_list.html
{% extends "common/base.html" %}
{% block content %}
     {% include 'common/messaging.html' %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">All Premises</h3>
        <a href="{% url 'parking_premises:premises_create' %}" class="btn btn-primary" style="float: right;">
            <span class="badge bg-primary">Add Premises</span>
        </a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Premises Name</th>
                <th>Address</th>
                <th>Authorized Person Name</th>
                <th>Authorized Person Contact</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for premises_obj in all_premises %}
            <tr>
                <td>{{ premises_obj.premise_name }}</td>
                <td>{{ premises_obj.address }}</td>
                <td>{{ premises_obj.authorized_person_name }}</td>
                <td>{{ premises_obj.authorized_person_contact }}</td>
                <td>{{ premises_obj.get_status_display }}</td>
                <td>
                    <a href="{% url 'parking_premises:premises_delete' premises_obj.id %}">
                        <span class="badge bg-danger">Delete</span>
                    </a>
<!--                    <span class="badge bg-success">Edit</span>-->
<!--                    <span class="badge bg-warning">Add slot</span>-->
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        {% include "common/pegination.html" %}
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {

    });
</script>
{% endblock%}

pms/templates/premises/slot_create.html
{% extends "common/base.html" %}
{% block content %}
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Slot Form</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label>Premises Name</label>
                {{ form.premise_slot }}
            </div>
             <div class="form-group">
                <label>Address</label>
                {{ form.vehicle_type }}
            </div>
            <div class="form-group">
                <label>Authorized Person Name</label>
                {{ form.price }}
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {

    });

</script>
{% endblock%}

pms/templates/premises/slot_list.html
{% extends "common/base.html" %}
{% block content %}
{% include 'common/messaging.html' %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">All Slots</h3>
        <a href="{% url 'parking_premises:slot_create' %}" class="btn btn-primary" style="float: right;">
            <span class="badge bg-primary">Add Slot</span>
        </a>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Premises Name</th>
                <th>Vehicle Type</th>
                <th>Price</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for slot_obj in all_slots %}
            <tr>
                <td>{{ slot_obj.premise_slot.premise_name }}</td>
                <td>{{ slot_obj.get_vehicle_type_display }}</td>
                <td>{{ slot_obj.price }}</td>
                <td>{{ slot_obj.get_status_display }}</td>
                <td>
                    <a href="{% url 'parking_premises:slot_delete' slot_obj.id %}">
                        <span class="badge bg-danger">Delete</span>
                    </a>
                    <!--                    <span class="badge bg-success">Edit</span>-->
                    <!--                    <span class="badge bg-warning">Add slot</span>-->
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer clearfix">
        {% include "common/pegination.html" %}
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {

    });

</script>
{% endblock%}